[options]
db_host = aios-postgres.c8fesmmgexe9.us-east-1.rds.amazonaws.com
db_port = 5432
db_user = aiosadmin
db_password = AI0sDBpass2026
db_name = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons
