[general]

[internal]
exten => 1001,1,Dial(SIP/1001,30)
exten => 1001,2,VoiceMail(1001@default)
exten => 1002,1,Dial(SIP/1002,30)
exten => 1002,2,VoiceMail(1002@default)
exten => 1003,1,Dial(SIP/1003,30)
exten => 1003,2,VoiceMail(1003@default)

exten => 9000,1,Answer()
exten => 9000,2,Wait(1)
exten => 9000,3,AGI(dograh://supervisor)
exten => 9000,4,Hangup()

[public]
exten => _X.,1,Playback(hello)
exten => _X.,2,Hangup()
